services:
  web:
    build: .
    image: gin-boilerplate/api:latest
    container_name: gin-boilerplate-api
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./:/app
    ports:
      - "${APP_EXPOSE_PORT}:${APP_PORT}"
