package application_test

import (
	"bytes"
	"encoding/json"
	"fmt"
	"gin-boilerplate/database/migration"
	"gin-boilerplate/internal/tester"
	"gin-boilerplate/pkg"
	"gin-boilerplate/pkg/routes"
	"github.com/gin-gonic/gin"
	"github.com/go-playground/assert/v2"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"strconv"
	"testing"
)

type TestSettingModel struct {
	id    uint
	user  migration.User
	token *migration.AuthenticationToken
}

var TestSetting = TestSettingModel{}

func TestAccountSetup(t *testing.T) {
	var env = "test"
	var bootstrap = pkg.InitBoot("../../../env.json", &env)

	// Set Gin to Test mode
	gin.SetMode(gin.TestMode)

	// routes
	routes.V1Routes(bootstrap)

	// reset the mock data
	bootstrap.DB.Where("slug = ?", "test_abc").Delete(&migration.Setting{})

	// mock authentication
	var user, token = tester.GenerateAuthentication(bootstrap, "admin", "admin_test")
	TestSetting.user = user
	TestSetting.token = token
}

func TestAccountInformationHttp(t *testing.T) {
	var env = "test"
	var bootstrap = pkg.InitBoot("../../../env.json", &env)

	// Set Gin to Test mode
	gin.SetMode(gin.TestMode)

	// routes
	routes.V1Routes(bootstrap)

	// Create a new multipart writer
	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)

	// Add other fields
	_ = writer.WriteField("first_name", "User")
	_ = writer.WriteField("last_name", "One")

	// Close multipart writer
	err := writer.Close()
	if err != nil {
		t.Error("Error closing writer:", err)
	}

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("PATCH", "/v1/account/information", body)
	req.Header.Set("Content-Type", writer.FormDataContentType())
	req.Header.Set("X-Secret-Key", bootstrap.Env.App.Key)
	req.Header.Set("Authorization", TestSetting.token.Token)
	bootstrap.Engine.ServeHTTP(w, req)

	if http.StatusOK != w.Code {
		fmt.Println("Err Body", w.Body.String())
	}

	var user = migration.User{}
	bootstrap.DB.Where("id = ?", TestSetting.user.Id).First(&user)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Equal(t, "User", user.FirstName)
	assert.Equal(t, "One", user.LastName.String)
}

func TestCreateSettingHttp(t *testing.T) {
	var env = "test"
	var bootstrap = pkg.InitBoot("../../../env.json", &env)

	// Set Gin to Test mode
	gin.SetMode(gin.TestMode)

	// routes
	routes.V1Routes(bootstrap)

	// Create a new multipart writer
	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)

	// Add other fields
	_ = writer.WriteField("name", "test")
	_ = writer.WriteField("slug", "test_abc")
	_ = writer.WriteField("type", "string")
	_ = writer.WriteField("is_disabled", "1")
	_ = writer.WriteField("is_public", "1")

	// Close multipart writer
	err := writer.Close()
	if err != nil {
		t.Error("Error closing writer:", err)
	}

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("POST", "/v1/settings", body)
	req.Header.Set("Content-Type", writer.FormDataContentType())
	req.Header.Set("X-Secret-Key", bootstrap.Env.App.Key)
	req.Header.Set("Authorization", TestSetting.token.Token)
	bootstrap.Engine.ServeHTTP(w, req)

	type AutoGenerated struct {
		Data int `json:"data"`
	}

	var data AutoGenerated
	res := w.Body.Bytes()
	err = json.Unmarshal(res, &data)
	if err != nil {
		// Handle error
		t.Error("Error json converting:", err)
	}

	if http.StatusOK != w.Code {
		fmt.Println("Err Body", w.Body.String())
	}

	var setting = migration.Setting{}
	bootstrap.DB.Where("id = ?", data.Data).First(&setting)

	TestSetting.id = setting.Id
	assert.Equal(t, http.StatusOK, w.Code)
	assert.Equal(t, "test", setting.Name)
	assert.Equal(t, "test_abc", setting.Slug)
}

func TestUpdateSettingHttp(t *testing.T) {
	var env = "test"
	var bootstrap = pkg.InitBoot("../../../env.json", &env)

	// Set Gin to Test mode
	gin.SetMode(gin.TestMode)

	// routes
	routes.V1Routes(bootstrap)

	// Create a new multipart writer
	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)

	// Add other fields
	_ = writer.WriteField("name", "test")
	_ = writer.WriteField("slug", "test_abc")
	_ = writer.WriteField("value", "test_value")
	_ = writer.WriteField("type", "string")
	_ = writer.WriteField("is_disabled", "1")
	_ = writer.WriteField("is_public", "1")

	// Close multipart writer
	err := writer.Close()
	if err != nil {
		t.Error("Error closing writer:", err)
	}

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("PATCH", "/v1/settings/"+strconv.Itoa(int(TestSetting.id)), body)
	req.Header.Set("Content-Type", writer.FormDataContentType())
	req.Header.Set("X-Secret-Key", bootstrap.Env.App.Key)
	req.Header.Set("Authorization", TestSetting.token.Token)
	bootstrap.Engine.ServeHTTP(w, req)

	type AutoGenerated struct {
		Data int `json:"data"`
	}

	var data AutoGenerated
	res := w.Body.Bytes()
	err = json.Unmarshal(res, &data)
	if err != nil {
		// Handle error
		t.Error("Error json converting:", err)
	}

	if http.StatusOK != w.Code {
		fmt.Println("Err Body", w.Body.String())
	}

	var setting = migration.Setting{}
	bootstrap.DB.Where("id = ?", strconv.Itoa(int(TestSetting.id))).First(&setting)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Equal(t, "test", setting.Name)
	assert.Equal(t, "test_value", setting.Value.String)
}

func TestSettingBrowseHttp(t *testing.T) {
	var env = "test"
	var bootstrap = pkg.InitBoot("../../../env.json", &env)

	// Set Gin to Test mode
	gin.SetMode(gin.TestMode)

	// routes
	routes.V1Routes(bootstrap)

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("GET", "/v1/settings", nil)
	req.Header.Set("X-Secret-Key", bootstrap.Env.App.Key)
	req.Header.Set("Authorization", TestSetting.token.Token)
	bootstrap.Engine.ServeHTTP(w, req)

	if http.StatusOK != w.Code {
		fmt.Println("Err Body", w.Body.String())
	}
	assert.Equal(t, http.StatusOK, w.Code)
}

func TestSettingViewHttp(t *testing.T) {
	var env = "test"
	var bootstrap = pkg.InitBoot("../../../env.json", &env)

	// Set Gin to Test mode
	gin.SetMode(gin.TestMode)

	// routes
	routes.V1Routes(bootstrap)

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("GET", "/v1/settings/"+strconv.Itoa(int(TestSetting.id)), nil)
	req.Header.Set("X-Secret-Key", bootstrap.Env.App.Key)
	req.Header.Set("Authorization", TestSetting.token.Token)
	bootstrap.Engine.ServeHTTP(w, req)

	if http.StatusOK != w.Code {
		fmt.Println("Err Body", w.Body.String())
	}
	assert.Equal(t, http.StatusOK, w.Code)
}

func TestSettingDeleteHttp(t *testing.T) {
	var env = "test"
	var bootstrap = pkg.InitBoot("../../../env.json", &env)

	// Set Gin to Test mode
	gin.SetMode(gin.TestMode)

	// routes
	routes.V1Routes(bootstrap)

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("DELETE", "/v1/settings/"+strconv.Itoa(int(TestSetting.id)), nil)
	req.Header.Set("X-Secret-Key", bootstrap.Env.App.Key)
	req.Header.Set("Authorization", TestSetting.token.Token)
	bootstrap.Engine.ServeHTTP(w, req)

	var setting = migration.Setting{}
	bootstrap.DB.Where("id = ?", strconv.Itoa(int(TestSetting.id))).First(&setting)

	if http.StatusOK != w.Code {
		fmt.Println("Err Body", w.Body.String())
	}
	assert.Equal(t, http.StatusOK, w.Code)
}

func TestSettingValuesHttp(t *testing.T) {
	var env = "test"
	var bootstrap = pkg.InitBoot("../../../env.json", &env)

	// Set Gin to Test mode
	gin.SetMode(gin.TestMode)

	// routes
	routes.V1Routes(bootstrap)

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("GET", "/v1/settings/values", nil)
	req.Header.Set("X-Secret-Key", bootstrap.Env.App.Key)
	req.Header.Set("Authorization", TestSetting.token.Token)
	bootstrap.Engine.ServeHTTP(w, req)

	if http.StatusOK != w.Code {
		fmt.Println("Err Body", w.Body.String())
	}
	assert.Equal(t, http.StatusOK, w.Code)
}
